#!/bin/sh

bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends -b --config ~/.config/picom/picom.conf &
feh --bg-fill ~/Pictures/wp2.jpg &
~/.config/polybar/launch.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config top_padding             40
bspc config bottom_padding          0
bspc config left_padding            0
bspc config right_padding           0

bspc config border_width            1
bspc config window_gap              12

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc config click_to_focus			none
bspc config focus_follows_pointer   true